#!/bin/bash

#SBATCH --job-name=phot_ni6

#SBATCH --output=A_phot_or_ni6.o

#SBATCH --error=A_phot_or_ni6.error

#SBATCH --partition=savio2_bigmem

#SBATCH --time=72:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=1

#SBATCH--cpus-per-task=24

# QoS: savio_normal

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=yves.robert@insa-lyon.fr
#SBATCH --mail-type=all

# run command
mkdir -p /global/scratch/$USER/$SLURM_JOB_ID
/global/software/sl-7.x86_64/modules/gcc/6.3.0/openmpi/2.0.2-gcc/bin/mpirun -np 4  /global/home/users/yvesrobert/serpent2.1.30_gcc/sss2 -omp 24 A_one_row_ni
