#!/bin/bash

#SBATCH --job-name=tr6_3

#SBATCH --output=tr6_3.o

#SBATCH --error=tr6_3.error

#SBATCH --partition=savio

#SBATCH --time=72:00:00

#SBATCH --nodes=8

#SBATCH --ntasks-per-node=1

#SBATCH--cpus-per-task=20

# QoS: savio_normal

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=yves.robert@insa-lyon.fr
#SBATCH --mail-type=all

# run command
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
mpirun -np 8 sss2 -omp 20 A_two_rows3
